# Generated by Django 5.1.6 on 2025-02-09 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('dop_title', models.CharField(blank=True, max_length=300, null=True)),
                ('dop_description1', models.TextField(blank=True, null=True)),
                ('dop_description2', models.TextField(blank=True, null=True)),
                ('dop_description3', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessIMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img_accessories/')),
                ('accessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_accessories', to='accessories.accessories')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=500)),
                ('value_parameter', models.TextField(blank=True, null=True)),
                ('accessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='accessories.accessories')),
            ],
        ),
    ]
