# Generated by Django 5.1.6 on 2025-02-15 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('accessor_discount', models.PositiveSmallIntegerField(blank=True, help_text='процент скидки', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrandAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccessIMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img_accessories/')),
                ('color', models.CharField(max_length=100)),
                ('accessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_accessories', to='accessories.accessories')),
            ],
        ),
        migrations.AddField(
            model_name='accessories',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_access', to='accessories.brandaccessories'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_access', to='accessories.categoryaccessories'),
        ),
        migrations.CreateModel(
            name='ParameterAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=500)),
                ('value_parameter', models.TextField(blank=True, null=True)),
                ('accessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='accessories.accessories')),
            ],
        ),
    ]
