# Generated by Django 5.1.6 on 2025-02-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessimg',
            name='color',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessories',
            name='accessor_discount',
            field=models.PositiveSmallIntegerField(blank=True, help_text='процент скидки', null=True),
        ),
    ]
