# Generated by Django 5.1.6 on 2025-02-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_accessimg_color_accessories_accessor_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='dop_description1',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='dop_description2',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='dop_description3',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='dop_title',
        ),
    ]
