# Generated by Django 5.1.6 on 2025-02-13 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_laptop_available'),
        ('user', '0003_cartitem_laptop_img_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='laptops',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptop_item', to='laptop.laptop'),
        ),
    ]
