# Generated by Django 5.1.6 on 2025-02-15 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('laptop_discount', models.PositiveSmallIntegerField(blank=True, help_text='процент скидки', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_laptop', to='laptop.brandlaptop')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_laptop', to='laptop.categorylaptop')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_title', models.CharField(max_length=100)),
                ('characteristic_description', models.TextField(blank=True, null=True)),
                ('laptop_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_laptop', to='laptop.laptop')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='laptop_photo/')),
                ('color', models.CharField(max_length=150)),
                ('laptop_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_laptop', to='laptop.laptop')),
            ],
        ),
    ]
