# Generated by Django 5.1.6 on 2025-02-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
